<?php

/**
 * @var AndPhone\YourApi\Block\ApiIndex $block
 */
?>
<div class="body">
    <title>API List:</title>
    <ul class="list">
        <li class="list-item">
            <h3 class="label">Get all products:</h3>
            <a class="link" href="http://andphone.xyz/rest/V1/custom-api/products" target="_blank">http://andphone.xyz/rest/V1/custom-api/products</a>
        </li>
        <li class="list-item">
            <h3 class="label">Get product by ID:</h3>
            <p><em>http://andphone.xyz/rest/V1/product/:id</em> (replace id with product ID)</p>
            <p>Example: <a class="link" href="http://andphone.xyz/rest/V1/custom-api/product/1" target="_blank">http://andphone.xyz/rest/V1/custom-api/product/1</a></p>
        </li>
        <li class="list-item">
            <h3 class="label">Get all categories:</h3>
            <a class="link" href="http://andphone.xyz/rest/V1/custom-api/categories" target="_blank">http://andphone.xyz/rest/V1/custom-api/categories</a>
        </li>
        <li class="list-item">
            <h3 class="label">Get products by category ID:</h3>
            <p><em>http://andphone.xyz/rest/V1/products/category/:id</em> (replace id with category ID)</p>
            <p>Example: <a class="link" href="http://andphone.xyz/rest/V1/custom-api/products/category/2" target="_blank">http://andphone.xyz/rest/V1/custom-api/products/category/2</a></p>
        </li>
    </ul>
</div>
